const MSGALERT = 'MSGALERT';
const CLEARMSGALERT = 'CLEARMSGALERT';
const MSGMODAL = 'MSGMODAL';
const STATEMENT = 'STATEMENT';
export {
    MSGALERT,
    MSGMODAL,
    STATEMENT,
    CLEARMSGALERT
};
